# Generated by Django 5.1.2 on 2026-03-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nce", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ncecollectionlog",
            options={"ordering": ["-collected_at"]},
        ),
        migrations.AlterModelOptions(
            name="ncedevice",
            options={"ordering": ["device_name"]},
        ),
        migrations.AlterModelOptions(
            name="ncepmdata",
            options={"ordering": ["-collection_time"]},
        ),
        migrations.AlterField(
            model_name="ncecollectionlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ncecollectionlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("error", "Error"),
                    ("skipped", "Omitido"),
                    ("dry_run", "Dry Run"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ncedevice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ncepmdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="ncepmdata",
            index=models.Index(
                fields=["pm_code", "device_name", "collection_time"],
                name="nce_pm_data_pm_code_261a47_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="ncecollectionlog",
            table="nce_collection_log",
        ),
        migrations.AlterModelTable(
            name="ncedevice",
            table="nce_device",
        ),
        migrations.AlterModelTable(
            name="ncepmdata",
            table="nce_pm_data",
        ),
    ]
