from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(blank=True, max_length=50, null=True)),
                ('orden_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_material', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo_art', models.CharField(blank=True, max_length=50, null=True)),
                ('descrip_gpo_art', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_valoracion', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_el_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por_sap', models.CharField(blank=True, max_length=100, null=True)),
                ('sujeto_lote', models.CharField(blank=True, max_length=10, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_naciones', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo_art_ext', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_subcat', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_subcat', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil_numserie', models.CharField(blank=True, max_length=50, null=True)),
                ('marcado_borrar', models.CharField(blank=True, max_length=10, null=True)),
                ('texto_pedido', models.CharField(blank=True, max_length=500, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('part_number', models.CharField(blank=True, max_length=200, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('centro', models.CharField(blank=True, max_length=50, null=True)),
                ('almacen', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_averia', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('valor_lote', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo_asignacion', models.CharField(blank=True, max_length=500, null=True)),
                ('estatus', models.CharField(blank=True, default='En Inventario', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Spare', 'verbose_name_plural': 'Spares'},
        ),
        migrations.CreateModel(
            name='SAPCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(db_index=True, max_length=100, unique=True)),
                ('texto_breve', models.TextField(blank=True, null=True)),
                ('denom_tpmt', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_material', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_art', models.CharField(blank=True, max_length=100, null=True)),
                ('descrip_gpo_art', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_valoracion', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_el', models.CharField(blank=True, max_length=50, null=True)),
                ('sujeto_lote', models.CharField(blank=True, max_length=10, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_naciones', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_art_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_subcat', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_subcat', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil_numserie', models.CharField(blank=True, max_length=100, null=True)),
                ('marcado_borrar', models.CharField(blank=True, max_length=10, null=True)),
                ('texto_pedido', models.CharField(blank=True, max_length=300, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'sap_catalog', 'verbose_name': 'Material SAP', 'verbose_name_plural': 'Catálogo SAP'},
        ),
        migrations.CreateModel(
            name='CentroAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=50)),
                ('almacen', models.CharField(max_length=50)),
            ],
            options={'db_table': 'centro_almacen', 'ordering': ['centro', 'almacen'], 'unique_together': {('centro', 'almacen')}},
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(blank=True, max_length=100, null=True)),
                ('part_number', models.CharField(max_length=200, unique=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={'db_table': 'part_number', 'ordering': ['proveedor', 'part_number'], 'unique_together': {('part_number', 'proveedor')}},
        ),
        migrations.CreateModel(
            name='SAPMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('material', models.CharField(db_index=True, max_length=100)),
                ('texto_breve', models.TextField(blank=True, null=True)),
                ('centro', models.CharField(blank=True, max_length=50, null=True)),
                ('almacen', models.CharField(blank=True, max_length=50, null=True)),
                ('status_sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('lote_stock', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_stock', models.CharField(blank=True, max_length=100, null=True)),
                ('modificado_el', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('modificado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_el', models.DateField(blank=True, null=True)),
                ('equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'sap_material'},
        ),
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_solicitante', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_login', models.CharField(blank=True, max_length=100, null=True)),
                ('red', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('ne', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo_ne', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=200, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('sn_averiada', models.CharField(blank=True, max_length=200, null=True)),
                ('rma_proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket_proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('sr_proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('sap_asignado', models.CharField(blank=True, max_length=50, null=True)),
                ('pn_asignado', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_asignado', models.CharField(blank=True, max_length=500, null=True)),
                ('sn_asignado', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_sn_asignado', models.DateField(blank=True, null=True)),
                ('fecha_inicio_rma', models.DateField(blank=True, null=True)),
                ('sn_rma', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_retorno', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='PENDIENTE', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockSAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('centro', models.CharField(blank=True, max_length=50, null=True)),
                ('almacen', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(blank=True, max_length=50, null=True)),
                ('sap', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('cantidad_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_asignacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_site', models.CharField(blank=True, max_length=100, null=True)),
                ('elemento_pep', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('folio', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_folio', models.CharField(blank=True, max_length=200, null=True)),
                ('status_folio', models.CharField(blank=True, max_length=50, null=True)),
                ('oym_encargado', models.CharField(blank=True, max_length=200, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoSpare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(blank=True, max_length=50, null=True)),
                ('sap', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('serial_lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad / N° Serie')),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_asignacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_site', models.CharField(blank=True, max_length=100, null=True)),
                ('elemento_pep', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('folio', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_folio', models.CharField(blank=True, max_length=200, null=True)),
                ('status_folio', models.CharField(blank=True, max_length=50, null=True)),
                ('oym_encargado', models.CharField(blank=True, max_length=200, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'seguimiento_spare'},
        ),
    ]
