# Generated by Django 5.1.2 on 2026-03-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0007_seguimiento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="centroalmacen",
            options={
                "ordering": ["centro", "almacen"],
                "verbose_name": "Centro / Almacén",
                "verbose_name_plural": "Centros / Almacenes",
            },
        ),
        migrations.AlterModelOptions(
            name="partnumber",
            options={
                "ordering": ["proveedor", "part_number"],
                "verbose_name": "Part Number",
                "verbose_name_plural": "Part Numbers",
            },
        ),
        migrations.AlterModelOptions(
            name="seguimiento",
            options={"ordering": ["-fecha_asignacion", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="spare",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Spare",
                "verbose_name_plural": "Spares",
            },
        ),
        migrations.AlterField(
            model_name="centroalmacen",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rma",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sapcatalog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sapmaterial",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="seguimiento",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="seguimiento",
            name="motivo_asignacion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seguimiento",
            name="red",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="seguimiento",
            name="status_folio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Concluido", "Concluido"),
                    ("No se Utilizó", "No se Utilizó"),
                    ("Pendiente Crear", "Pendiente Crear"),
                    ("Aprobado", "Aprobado"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="seguimientospare",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="seguimientospare",
            name="oym_encargado",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="OyM Encargado"
            ),
        ),
        migrations.AlterField(
            model_name="seguimientospare",
            name="red",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IPRAN", "IPRAN"),
                    ("CORE", "CORE"),
                    ("METRO", "METRO"),
                    ("ACCESO", "ACCESO"),
                    ("OTRO", "OTRO"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="seguimientospare",
            name="serial_lote",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Cantidad / N° Serie",
            ),
        ),
        migrations.AlterField(
            model_name="seguimientospare",
            name="status_folio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aprobado", "Aprobado"),
                    ("Pendiente Crear", "Pendiente Crear"),
                    ("Concluido", "Concluido"),
                    ("No se Utilizó", "No se Utilizó"),
                    ("Pendiente", "Pendiente"),
                    ("Cancelado", "Cancelado"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spare",
            name="cat_valoracion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="centro",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="cod_naciones",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="cod_subcat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="estatus",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="spare",
            name="etiqueta",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="grupo_art",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="grupo_art_ext",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="spare",
            name="motivo_asignacion",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="orden_compra",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="perfil_numserie",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="proveedor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="sap",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="spare",
            name="serial_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="spare",
            name="texto_pedido",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="tipo_material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="unidad_medida",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="spare",
            name="valor_lote",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stocksap",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterModelTable(
            name="seguimiento",
            table="seguimiento",
        ),
        migrations.AlterModelTable(
            name="spare",
            table="spare",
        ),
    ]
