# Generated by Django 4.2.29 on 2026-03-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0008_alter_centroalmacen_options_alter_partnumber_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seguimiento",
            name="proveedor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
