# Generated by Django 4.2.29 on 2026-03-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0009_seguimiento_proveedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeguimientoAveriadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("red", models.CharField(blank=True, max_length=100, null=True)),
                ("proveedor", models.CharField(blank=True, max_length=200, null=True)),
                ("equipo", models.CharField(blank=True, max_length=200, null=True)),
                ("modelo", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "part_number_averiado",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "serie_averiada",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sap", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "encargado_oym",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ingresado_almacen",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "acta_ingreso",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "incidencia_oym",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fecha_cambio_retiro", models.DateField(blank=True, null=True)),
                ("fecha_correo_oym", models.DateField(blank=True, null=True)),
                ("fecha_correo_proveedor", models.DateField(blank=True, null=True)),
                ("rma", models.CharField(blank=True, max_length=200, null=True)),
                ("ticket", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "costo_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seguimiento_averiadas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeguimientoUpgrades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("proveedor", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "part_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sap", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("cantidad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "numero_serie",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fecha_asignacion", models.DateField(blank=True, null=True)),
                (
                    "guia_remision",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("folio", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "numero_pedido",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("motivo_asignacion", models.TextField(blank=True, null=True)),
                ("seguimiento", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seguimiento_upgrades",
                "ordering": ["-created_at"],
            },
        ),
    ]
