# Generated by Django 4.2.29 on 2026-03-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0010_seguimientoaveriadas_seguimientoupgrades"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeguimientoProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("proveedor", models.CharField(blank=True, max_length=200, null=True)),
                ("sap", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "part_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "numero_serie",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("lote", models.CharField(blank=True, max_length=100, null=True)),
                ("centro", models.CharField(blank=True, max_length=100, null=True)),
                ("almacen", models.CharField(blank=True, max_length=100, null=True)),
                ("motivo_asignacion", models.TextField(blank=True, null=True)),
                ("fecha_asignacion", models.DateField(blank=True, null=True)),
                ("fecha_devolucion", models.DateField(blank=True, null=True)),
                (
                    "gr_devolucion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("estado", models.CharField(blank=True, max_length=100, null=True)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seguimiento_proveedor",
                "ordering": ["-created_at"],
            },
        ),
    ]
