# Generated by Django 4.2.29 on 2026-03-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0011_seguimientoproveedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnumber",
            name="comentarios",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partnumber",
            name="modelo_equipo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="partnumber",
            name="tipo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
