# Generated by Django 4.2.29 on 2026-03-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0012_partnumber_comentarios_partnumber_modelo_equipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="centroalmacen",
            name="denom_almacen",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
