# Generated by Django 4.2.29 on 2026-04-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0014_update_spare_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpareValorado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "centro",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("almacen", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "material",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "numero_serie",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "numero_equipo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fecha_evaluacion", models.DateField(blank=True, null=True)),
                ("dias", models.IntegerField(blank=True, null=True)),
                ("antiguedad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("unidad", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "precio_medio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "tipo_cambio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("fecha_oc", models.DateField(blank=True, null=True)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("fecha_ultima_modif", models.DateField(blank=True, null=True)),
                (
                    "perfil_serie",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tipo_stock", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "solicitante",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("numero_oc", models.CharField(blank=True, max_length=100, null=True)),
                ("posicion_oc", models.CharField(blank=True, max_length=50, null=True)),
                ("comprador", models.CharField(blank=True, max_length=200, null=True)),
                ("fecha_extraccion", models.DateField(blank=True, null=True)),
                ("lote", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "clase_movimiento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("almacen_de", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contrata_simple",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tipo_alma", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "clase_almacen",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contrata", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "responsable",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "gerente_resp",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "subdirector",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("jefe_resp", models.CharField(blank=True, max_length=200, null=True)),
                ("resp_oc", models.CharField(blank=True, max_length=200, null=True)),
                ("accion", models.CharField(blank=True, max_length=300, null=True)),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "modelo_equipo",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "rot_despacho_centro",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "rot_consumo_centro",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "antiguedad2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "macroproyecto",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "rot_despacho_total",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "rot_consumo_total",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "tipo_material",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tipo_material2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("proveedor", models.CharField(blank=True, max_length=300, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spare Valorado",
                "verbose_name_plural": "Spares Valorados",
                "db_table": "spare_valorado",
                "ordering": ["centro", "almacen", "material"],
            },
        ),
    ]
