# Generated by Django 4.2.29 on 2026-04-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0015_sparevalorado"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpareValorado",
        ),
        migrations.AddField(
            model_name="spare",
            name="pedido_traslado",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="spare",
            name="procedencia",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
