# Generated by Django 4.2.29 on 2026-05-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0020_add_spare_indexes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="spare",
            name="unique_spare_sap_serial",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_estatus_idx",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_tipo_idx",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_centro_idx",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_almacen_idx",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_proveedor_idx",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_sap_idx",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_oc_idx",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_fi_idx",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_sap_est_idx",
        ),
        migrations.RemoveIndex(
            model_name="spare",
            name="spare_oc_est_idx",
        ),
    ]
