# Generated by Django 4.2.29 on 2026-05-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0024_delete_seguimiento_spare"),
    ]

    operations = [
        migrations.AddField(
            model_name="seguimientoaveriadas",
            name="modalidad_entrega",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="seguimientoaveriadas",
            name="serie_proveedor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="seguimiento",
            name="status_folio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Concluido", "Concluido"),
                    ("No se Utilizó", "No se Utilizó"),
                    ("Pendiente Crear", "Pendiente Crear"),
                    ("Aprobado", "Aprobado"),
                ],
                db_index=True,
                max_length=100,
                null=True,
            ),
        ),
    ]
