# Generated by Django 4.2.29 on 2026-05-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spare", "0025_seguimientoaveriadas_modalidad_entrega_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeguimientoProveedor",
        ),
    ]
