# Generated by Django 6.0.6 on 2026-06-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0030_spare_rename_pedido_traslado'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='responsable_oc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
