# Generated by Django 4.2.29 on 2026-08-29 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("filename", models.CharField(blank=True, max_length=300, null=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("rows_total", models.IntegerField(default=0)),
                ("rows_loaded", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("skipped", "Omitido"),
                            ("dry_run", "Dry Run"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "nc_collection_log",
                "ordering": ["-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("P", "P (Core)"), ("PE", "PE"), ("BR", "BR")],
                        max_length=5,
                    ),
                ),
                ("role_manual", models.BooleanField(default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "db_table": "nc_device",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("twamp", "TWAMP"),
                            ("telemetry", "Telemetría (IPInterface)"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="netcore.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interfaz",
                "verbose_name_plural": "Interfaces",
                "db_table": "nc_interface",
                "ordering": ["device__name", "name"],
                "unique_together": {("device", "name")},
            },
        ),
        migrations.CreateModel(
            name="TrafficSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(db_index=True, max_length=200)),
                ("interface_name", models.CharField(db_index=True, max_length=300)),
                ("collected_at", models.DateTimeField(db_index=True)),
                ("in_rate_avg", models.FloatField(blank=True, null=True)),
                ("out_rate_avg", models.FloatField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("filename", models.CharField(blank=True, max_length=300)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="traffic_samples",
                        to="netcore.interface",
                    ),
                ),
            ],
            options={
                "db_table": "nc_traffic_sample",
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["device_name", "interface_name", "collected_at"],
                        name="nc_traffic__device__f96293_idx",
                    )
                ],
                "unique_together": {("device_name", "interface_name", "collected_at")},
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity_gbps", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "delay_threshold_ms",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "utilization_threshold_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interface_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_a",
                        to="netcore.interface",
                    ),
                ),
                (
                    "interface_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_b",
                        to="netcore.interface",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enlace",
                "verbose_name_plural": "Enlaces",
                "db_table": "nc_link",
                "unique_together": {("interface_a", "interface_b")},
            },
        ),
        migrations.CreateModel(
            name="DelaySample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_device", models.CharField(db_index=True, max_length=200)),
                ("dest_device", models.CharField(db_index=True, max_length=200)),
                ("queue", models.CharField(db_index=True, max_length=20)),
                ("resource_id", models.CharField(db_index=True, max_length=100)),
                ("collected_at", models.DateTimeField(db_index=True)),
                ("delay_avg_ms", models.FloatField(blank=True, null=True)),
                ("delay_max_ms", models.FloatField(blank=True, null=True)),
                ("delay_min_ms", models.FloatField(blank=True, null=True)),
                ("jitter_ms", models.FloatField(blank=True, null=True)),
                ("packet_loss_pct", models.FloatField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("filename", models.CharField(blank=True, max_length=300)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delay_samples",
                        to="netcore.interface",
                    ),
                ),
            ],
            options={
                "db_table": "nc_delay_sample",
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["source_device", "dest_device", "collected_at"],
                        name="nc_delay_sa_source__b9a14f_idx",
                    )
                ],
                "unique_together": {("resource_id", "collected_at")},
            },
        ),
    ]
