# Generated by Django 4.2.29 on 2026-09-01 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("netcore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="device_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="links_as_b",
                to="netcore.device",
            ),
        ),
    ]
