# Generated by Django 4.2.29 on 2026-09-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netcore", "0002_link_device_b"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="pbi_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
