# Generated by Django 4.2.29 on 2026-09-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netcore", "0003_link_pbi_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="speed_gbps",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
    ]
