# Generated by Django 4.2.29 on 2026-09-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("netcore", "0004_interface_speed_gbps"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityMonthly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                (
                    "disponibilidad_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("muestras_total", models.IntegerField(default=0)),
                ("muestras_caidas", models.IntegerField(default=0)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidad_mensual",
                        to="netcore.link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidad mensual",
                "verbose_name_plural": "Disponibilidad mensual",
                "db_table": "nc_availability_monthly",
                "ordering": ["-year", "-month"],
                "unique_together": {("link", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="AvailabilityDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(db_index=True)),
                (
                    "disponibilidad_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("muestras_total", models.IntegerField(default=0)),
                ("muestras_caidas", models.IntegerField(default=0)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidad_diaria",
                        to="netcore.link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidad diaria",
                "verbose_name_plural": "Disponibilidad diaria",
                "db_table": "nc_availability_daily",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["link", "fecha"], name="nc_availabi_link_id_c60e3d_idx"
                    )
                ],
                "unique_together": {("link", "fecha")},
            },
        ),
    ]
