# Generated by Django 4.2.29 on 2026-10-08 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModeloAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.CharField(blank=True, max_length=150)),
                ("alias", models.CharField(max_length=100, unique=True)),
                ("modelo", models.CharField(max_length=100)),
                ("comentario", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "cat_modelo_alias",
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="NceCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_reporte",
                    models.DateTimeField(
                        help_text='"Save Time" del reporte (UTC)', unique=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("procesando", "Procesando"),
                            ("ok", "OK"),
                            ("error", "Error"),
                        ],
                        default="procesando",
                        max_length=20,
                    ),
                ),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("fin", models.DateTimeField(blank=True, null=True)),
                ("mensaje", models.TextField(blank=True)),
            ],
            options={
                "db_table": "nce_carga",
                "ordering": ["-fecha_reporte"],
            },
        ),
        migrations.CreateModel(
            name="NceNe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ne_name", models.CharField(max_length=150, unique=True)),
                ("nce_ne_id", models.CharField(blank=True, max_length=50)),
                ("red_confirmada", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "db_table": "nce_ne",
                "ordering": ["ne_name"],
            },
        ),
        migrations.CreateModel(
            name="Red",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=50)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "cat_red",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.CharField(blank=True, max_length=150)),
                ("modelo", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=40)),
                ("parche", models.CharField(blank=True, max_length=40)),
                ("comentario", models.CharField(blank=True, max_length=255)),
                (
                    "red",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targets",
                        to="inventario.red",
                    ),
                ),
            ],
            options={
                "db_table": "cat_sw_target",
                "ordering": ["red__orden", "modelo"],
            },
        ),
        migrations.CreateModel(
            name="NceNeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ne_type", models.CharField(max_length=100)),
                ("ip", models.CharField(blank=True, max_length=45)),
                (
                    "software",
                    models.CharField(
                        blank=True, help_text="Texto original del NCE", max_length=200
                    ),
                ),
                (
                    "patch_list",
                    models.CharField(
                        blank=True, help_text="Texto original del NCE", max_length=200
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Versión normalizada, ej. V800R022C00SPC600",
                        max_length=40,
                    ),
                ),
                (
                    "parche",
                    models.CharField(
                        blank=True,
                        help_text="Parche(s) sin el SPC, ej. SPH122",
                        max_length=60,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, help_text="Running Status del NCE", max_length=40
                    ),
                ),
                ("creado_en_nce", models.DateTimeField(blank=True, null=True)),
                ("subnet_path", models.CharField(blank=True, max_length=255)),
                ("subnet", models.CharField(blank=True, max_length=150)),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nes",
                        to="inventario.ncecarga",
                    ),
                ),
                (
                    "ne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="inventario.ncene",
                    ),
                ),
            ],
            options={
                "db_table": "nce_ne_snapshot",
            },
        ),
        migrations.AddField(
            model_name="ncene",
            name="red",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nes",
                to="inventario.red",
            ),
        ),
        migrations.CreateModel(
            name="NceCargaArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_reporte", models.CharField(max_length=40)),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("filas", models.PositiveIntegerField(default=0)),
                ("hash_sha256", models.CharField(max_length=64, unique=True)),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="inventario.ncecarga",
                    ),
                ),
            ],
            options={
                "db_table": "nce_carga_archivo",
            },
        ),
        migrations.CreateModel(
            name="EosSoftware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.CharField(blank=True, max_length=150)),
                ("modelo", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=40)),
                ("fecha_eos", models.DateField()),
                ("comentario", models.CharField(blank=True, max_length=255)),
                (
                    "red",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eos_software",
                        to="inventario.red",
                    ),
                ),
            ],
            options={
                "db_table": "cat_eos_software",
                "ordering": ["red__orden", "modelo", "version"],
            },
        ),
        migrations.CreateModel(
            name="EosHardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.CharField(blank=True, max_length=150)),
                ("modelo", models.CharField(max_length=100)),
                ("fecha_eos", models.DateField()),
                ("comentario", models.CharField(blank=True, max_length=255)),
                (
                    "red",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eos_hardware",
                        to="inventario.red",
                    ),
                ),
            ],
            options={
                "db_table": "cat_eos_hardware",
                "ordering": ["red__orden", "modelo"],
            },
        ),
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tabla", models.CharField(max_length=64)),
                ("registro_id", models.BigIntegerField(null=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("editar", "Editar"),
                            ("borrar", "Borrar"),
                            ("importar", "Importar"),
                        ],
                        max_length=10,
                    ),
                ),
                ("antes", models.JSONField(blank=True, null=True)),
                ("despues", models.JSONField(blank=True, null=True)),
                ("usuario", models.CharField(max_length=150)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "app_auditoria",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["tabla", "registro_id"], name="ix_auditoria_registro"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="softwaretarget",
            constraint=models.UniqueConstraint(
                fields=("red", "modelo"), name="uq_sw_target_red_modelo"
            ),
        ),
        migrations.AddIndex(
            model_name="ncenesnapshot",
            index=models.Index(
                fields=["carga", "ne_type"], name="ix_snapshot_carga_tipo"
            ),
        ),
        migrations.AddConstraint(
            model_name="ncenesnapshot",
            constraint=models.UniqueConstraint(
                fields=("carga", "ne"), name="uq_snapshot_carga_ne"
            ),
        ),
        migrations.AddConstraint(
            model_name="ncecargaarchivo",
            constraint=models.UniqueConstraint(
                fields=("carga", "tipo_reporte"), name="uq_carga_tipo_reporte"
            ),
        ),
        migrations.AddConstraint(
            model_name="eossoftware",
            constraint=models.UniqueConstraint(
                fields=("red", "modelo", "version"), name="uq_eos_sw_red_modelo_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="eoshardware",
            constraint=models.UniqueConstraint(
                fields=("red", "modelo"), name="uq_eos_hw_red_modelo"
            ),
        ),
    ]
