# Generated by Django 4.2.29 on 2026-10-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_redes_iniciales"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.CharField(blank=True, max_length=150)),
                ("pn", models.CharField(max_length=60, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=500)),
                (
                    "elemento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Chasis", "Chasis"),
                            ("Board", "Board"),
                            ("SubBoard", "SubBoard"),
                            ("Transceiver", "Transceiver"),
                            ("Power", "Power"),
                            ("", "Sin definir"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inventariable", models.BooleanField(default=True)),
                (
                    "observacion",
                    models.CharField(
                        blank=True, help_text="Ej. Integrated", max_length=255
                    ),
                ),
            ],
            options={
                "db_table": "cat_part_number",
                "ordering": ["pn"],
            },
        ),
        migrations.CreateModel(
            name="SerialPartNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.CharField(blank=True, max_length=150)),
                ("serial", models.CharField(max_length=80, unique=True)),
                ("pn", models.CharField(max_length=60)),
                ("comentario", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "cat_serial_part_number",
                "ordering": ["serial"],
            },
        ),
        migrations.AddField(
            model_name="ncecarga",
            name="origen",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("automatica", "Automática"),
                    ("base_v75", "Base Excel V7.5"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReglaRedSubnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.CharField(blank=True, max_length=150)),
                ("segmento", models.CharField(max_length=100, unique=True)),
                (
                    "red",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglas_subnet",
                        to="inventario.red",
                    ),
                ),
            ],
            options={
                "db_table": "cat_regla_red_subnet",
                "ordering": ["segmento"],
            },
        ),
        migrations.CreateModel(
            name="NceComponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("frame", "Subrack"),
                            ("board", "Board"),
                            ("subboard", "Subcard"),
                            ("transceiver", "Optical module"),
                        ],
                        max_length=12,
                    ),
                ),
                ("ne_name", models.CharField(max_length=150)),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Board Name / Subboard Type / tipo óptico",
                        max_length=150,
                    ),
                ),
                ("slot", models.CharField(blank=True, max_length=10)),
                ("subslot", models.CharField(blank=True, max_length=10)),
                ("puerto", models.CharField(blank=True, max_length=100)),
                ("pn", models.CharField(blank=True, max_length=60)),
                ("sn", models.CharField(blank=True, max_length=80)),
                ("vendor_pn", models.CharField(blank=True, max_length=80)),
                ("port_custom", models.CharField(blank=True, max_length=150)),
                ("descripcion", models.CharField(blank=True, max_length=500)),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes",
                        to="inventario.ncecarga",
                    ),
                ),
            ],
            options={
                "db_table": "nce_componente",
                "indexes": [
                    models.Index(
                        fields=["carga", "tipo"], name="ix_componente_carga_tipo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InvItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="NE Type (Description Group)", max_length=100
                    ),
                ),
                (
                    "pn_chasis",
                    models.CharField(
                        blank=True, help_text="BOM Code Group", max_length=60
                    ),
                ),
                ("elemento", models.CharField(max_length=12)),
                ("nombre", models.CharField(max_length=150)),
                ("sr", models.CharField(default="1", max_length=10)),
                ("b", models.CharField(default=".", max_length=10)),
                ("s", models.CharField(default=".", max_length=10)),
                ("p", models.CharField(default=".", max_length=20)),
                ("pn", models.CharField(blank=True, max_length=60)),
                ("sn", models.CharField(blank=True, max_length=80)),
                ("descripcion", models.CharField(blank=True, max_length=500)),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventario.ncecarga",
                    ),
                ),
                (
                    "ne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventario.ncene",
                    ),
                ),
                (
                    "red",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventario.red",
                    ),
                ),
            ],
            options={
                "db_table": "inv_item",
                "indexes": [
                    models.Index(
                        fields=["carga", "elemento"], name="ix_item_carga_elemento"
                    ),
                    models.Index(fields=["carga", "red"], name="ix_item_carga_red"),
                    models.Index(fields=["carga", "sn"], name="ix_item_carga_sn"),
                    models.Index(fields=["carga", "pn"], name="ix_item_carga_pn"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        help_text="Fecha del reporte de la carga que detectó el cambio"
                    ),
                ),
                ("fecha_anterior", models.DateTimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("baja", "Baja"),
                            ("movimiento", "Movimiento"),
                        ],
                        max_length=12,
                    ),
                ),
                ("elemento", models.CharField(max_length=12)),
                ("red", models.CharField(max_length=20)),
                ("pn", models.CharField(blank=True, max_length=60)),
                ("sn", models.CharField(blank=True, max_length=80)),
                ("descripcion", models.CharField(blank=True, max_length=500)),
                ("ne_antes", models.CharField(blank=True, max_length=150)),
                ("ne_despues", models.CharField(blank=True, max_length=150)),
                ("pos_antes", models.CharField(blank=True, max_length=60)),
                ("pos_despues", models.CharField(blank=True, max_length=60)),
                (
                    "carga",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cambios",
                        to="inventario.ncecarga",
                    ),
                ),
            ],
            options={
                "db_table": "inv_cambio",
                "ordering": ["-fecha", "tipo", "elemento"],
                "indexes": [
                    models.Index(fields=["fecha", "tipo"], name="ix_cambio_fecha_tipo"),
                    models.Index(fields=["sn"], name="ix_cambio_sn"),
                ],
            },
        ),
    ]
