# Generated by Django 4.2.29 on 2026-10-09 01:40

from django.db import migrations

REGLAS = [
    ('CSR', 'Acceso'),
    ('IPRAN', 'IPRAN'),
    ('IP_MPLS', 'Fotonico'),
    ('CMETRO', 'Fotonico'),
    ('CLAN', 'Fotonico'),
    ('IP-FAN', 'Fotonico'),
]


def crear_reglas(apps, schema_editor):
    Red = apps.get_model('inventario', 'Red')
    ReglaRedSubnet = apps.get_model('inventario', 'ReglaRedSubnet')
    db = schema_editor.connection.alias
    for segmento, red in REGLAS:
        ReglaRedSubnet.objects.using(db).update_or_create(
            segmento=segmento,
            defaults={'red': Red.objects.using(db).get(codigo=red), 'actualizado_por': 'migración'})


def borrar_reglas(apps, schema_editor):
    ReglaRedSubnet = apps.get_model('inventario', 'ReglaRedSubnet')
    ReglaRedSubnet.objects.using(schema_editor.connection.alias).filter(
        segmento__in=[s for s, _ in REGLAS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_partnumber_serialpartnumber_ncecarga_origen_and_more"),   # ← el que generó Django
    ]

    operations = [
        migrations.RunPython(crear_reglas, borrar_reglas),
    ]
