# Generated by Django 4.2.29 on 2026-07-04 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BBEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                (
                    "rol",
                    models.CharField(
                        blank=True,
                        choices=[("P", "P (Core)"), ("PE", "PE"), ("BR", "BR")],
                        max_length=5,
                    ),
                ),
                ("rol_manual", models.BooleanField(default=False)),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "db_table": "bb_equipo",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="BBTrafico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(db_index=True, max_length=200)),
                ("resource", models.CharField(db_index=True, max_length=300)),
                ("collection_time", models.DateTimeField(db_index=True)),
                ("in_rate_avg", models.FloatField(blank=True, null=True)),
                ("out_rate_avg", models.FloatField(blank=True, null=True)),
                ("in_util_avg_pct", models.FloatField(blank=True, null=True)),
                ("out_util_avg_pct", models.FloatField(blank=True, null=True)),
                ("max_rate", models.FloatField(blank=True, null=True)),
                ("max_util_pct", models.FloatField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("filename", models.CharField(blank=True, max_length=300)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bb_trafico",
                "ordering": ["-collection_time"],
                "indexes": [
                    models.Index(
                        fields=["device_name", "resource", "collection_time"],
                        name="bb_trafico_device__61ac12_idx",
                    )
                ],
                "unique_together": {("device_name", "resource", "collection_time")},
            },
        ),
        migrations.CreateModel(
            name="BBDelay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_device", models.CharField(db_index=True, max_length=200)),
                ("dest_device", models.CharField(db_index=True, max_length=200)),
                ("cola", models.CharField(db_index=True, max_length=20)),
                ("collection_time", models.DateTimeField(db_index=True)),
                ("delay_avg_ms", models.FloatField(blank=True, null=True)),
                ("delay_max_ms", models.FloatField(blank=True, null=True)),
                ("delay_min_ms", models.FloatField(blank=True, null=True)),
                ("jitter_ms", models.FloatField(blank=True, null=True)),
                ("packet_loss_pct", models.FloatField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("filename", models.CharField(blank=True, max_length=300)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bb_delay",
                "ordering": ["-collection_time"],
                "indexes": [
                    models.Index(
                        fields=["source_device", "dest_device", "collection_time"],
                        name="bb_delay_source__37fa1a_idx",
                    )
                ],
                "unique_together": {
                    ("source_device", "dest_device", "cola", "collection_time")
                },
            },
        ),
        migrations.CreateModel(
            name="BBEnlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidad_gbps", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "umbral_delay_ms",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "umbral_uso_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("iface_origen", models.CharField(blank=True, max_length=300)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_destino",
                        to="backbone.bbequipo",
                    ),
                ),
                (
                    "origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_origen",
                        to="backbone.bbequipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enlace de core",
                "verbose_name_plural": "Enlaces de core",
                "db_table": "bb_enlace",
                "ordering": ["origen__nombre", "destino__nombre"],
                "unique_together": {("origen", "destino")},
            },
        ),
    ]
