# Generated by Django 4.2.29 on 2026-07-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backbone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BBCollectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pm_code", models.CharField(max_length=100)),
                ("filename", models.CharField(blank=True, max_length=300, null=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("rows_total", models.IntegerField(default=0)),
                ("rows_loaded", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("skipped", "Omitido"),
                            ("dry_run", "Dry Run"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "bb_collection_log",
                "ordering": ["-collected_at"],
            },
        ),
    ]
