# Generated by Django 4.2.29 on 2026-07-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backbone", "0002_bbcollectionlog"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bbdelay",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bbdelay",
            name="resource_id",
            field=models.CharField(db_index=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="bbdelay",
            unique_together={("resource_id", "collection_time")},
        ),
    ]
